[versions]
compileSdk = "35"
minSdk = "21"
targetSdk = "35"
agp = "8.11.0-alpha07"
kotlin = "2.2.0-Beta1"
[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }